### ISSUE TITLE
Improve the performance of the bridge service

### ISSUE THREAD

**Issue by cool-develope** [0xPolygonHermez/zkevm-bridge-service#286]
- [x] [#282] Split reads and writes, improve the storage reads performance using db replica
- [x] [#283, #284] Optimize the merkle tree operations
- [x] [#285] Refactor the merkle tree to avoid the duplication issue
- [x] [#307] Improve the reads perf in the bridge API using LRU cache
